### ISSUE TITLE
Missing license :)

### ISSUE THREAD

**Issue by r-lyeh** [w23/atto#1]
Hey, 

Found this repo when checking your other OpenSource prj.
I think you are missing a license file here (WTFPL?)

Keep up the good work
- r-lyeh

**Comment by w23** [comment]
github doesn't have wtfpl template ;_;

**Comment by r-lyeh** [comment]
I was thinking about adding parts or the whole atto library to my unlicensed engine.
Would you consider releasing under Unlicense/PublicDomain?
If not, what about dual licensing MIT+Unlicense?

Thanks!

**Comment by w23** [comment]
It is very flattening that you want to use this. Please do, and please report any issues you encounter. I’m sure there are quite a few (e.g. one known is that mouse input is broken on absolute devices, as touchscreens and vm input).
Consider it licensed to you as WTFPL :D. I will think about licensing it properly later, when I’m not on a phone.
